#!/usr/bin/env python
# -*- coding: utf-8 -*-

AF_INET = 0
AF_INET6 = 1

STATUS_NOT_STARTED = 0
STATUS_RUNNING = 1
STATUS_FINISHED = 2
STATUS_UNDETERMINED = 3

TESTBED_STATUS_ZERO = 0
TESTBED_STATUS_SETUP = 1
TESTBED_STATUS_CREATED = 2
TESTBED_STATUS_CONNECTED = 3
TESTBED_STATUS_CROSS_CONNECTED = 4
TESTBED_STATUS_CONFIGURED = 5
TESTBED_STATUS_STARTED = 6
TESTBED_STATUS_STOPPED = 7

TIME_NOW = "0s"


ATTR_NEPI_TESTBED_ENVIRONMENT_SETUP = "_nepi_testbed_environment_setup"

