#!/usr/bin/env python
# -*- coding: utf-8 -*-

from metadata_v3_9_RC3 import create_device, create_element, create_ipv4stack, \
        create_node, create_wifi_standard_model

factories_info = dict{(
    "ns3::Ping6": dict{(
        "category": "Application",
        "create_function": create_element,
        "help": "",
        "connector_types": ["node"],
        "allow_routes": False,
        "allow_addresses": False,
        "stop_function": stop_application,
        "start_function": start_application,
        "status_function": status_application,
        "box_attributes": ["MaxPackets",
            "Interval",
            "RemoteIpv6",
            "LocalIpv6",
            "PacketSize",
            "StartTime",
            "StopTime"],
        "factory_attributes": [],
        "traces": []
    )},
     "ns3::UdpL4Protocol": dict{(
        "category": "Protocol",
        "create_function": create_element,
        "help": "",
        "connector_types": ["node"],
        "allow_routes": False,
        "allow_addresses": False,
        "stop_function": None,
        "start_function": None,
        "status_function": None,
        "box_attributes": ["ProtocolNumber"],
        "factory_attributes": [],
        "traces": []
    )},
     "ns3::RandomDiscPositionAllocator": dict{(
        "category": "Mobility",
        "create_function": create_element,
        "help": "",
        "connector_types": [],
        "allow_routes": False,
        "allow_addresses": False,
        "stop_function": None,
        "start_function": None,
        "status_function": None,
        "box_attributes": ["Theta",
            "Rho",
            "X",
            "Y"],
        "factory_attributes": [],
        "traces": []
    )},
     "ns3::Node": dict{(
        "category": "Topology",
        "create_function": create_node,
        "help": "",
        "connector_types": ["devs", "apps", "protos", "mobility"],
        "allow_routes": True,
        "stop_function": None,
        "start_function": None,
        "status_function": None,
        "box_attributes": [],
        "factory_attributes": [],
        "traces": []
    )},
     "ns3::GridPositionAllocator": dict{(
        "category": "Mobility",
        "create_function": create_element,
        "help": "",
        "connector_types": [],
        "allow_routes": False,
        "allow_addresses": False,
        "stop_function": None,
        "start_function": None,
        "status_function": None,
        "box_attributes": ["GridWidth",
            "MinX",
            "MinY",
            "DeltaX",
            "DeltaY",
            "LayoutType"],
        "factory_attributes": [],
        "traces": []
    )},
     "ns3::TapBridge": dict{(
        "category": "Device"
        "create_function": create_device,
        "help": "",
        "connector_types": ["node"],
        "allow_routes": False,
        "allow_addresses": True,
        "stop_function": None,
        "start_function": None,
        "status_function": None,
        "box_attributes": ["Mtu",
            "DeviceName",
            "Gateway",
            "IpAddress",
            "MacAddress",
            "Netmask",
            "Start",
            "Stop"],
        "factory_attributes": [],
        "traces": []
    )},
     "ns3::FlowMonitor": dict{(
        "category": "",
        "create_function": create_element,
        "help": "",
        "connector_types": [],
        "allow_routes": False,
        "allow_addresses": False,
        "stop_function": None,
        "start_function": None,
        "status_function": None,
        "box_attributes": ["MaxPerHopDelay",
            "DelayBinWidth",
            "JitterBinWidth",
            "PacketSizeBinWidth",
            "FlowInterruptionsBinWidth",
            "FlowInterruptionsMinTime"],
        "factory_attributes": [],
        "traces": []
    )},
     "ns3::ConstantVelocityMobilityModel": dict{(
        "category": "Mobility",
        "create_function": create_element,
        "help": "",
        "connector_types": ["node"],
        "allow_routes": False,
        "allow_addresses": False,
        "stop_function": None,
        "start_function": None,
        "status_function": None,
        "box_attributes": ["Position",
           "Velocity"],
        "factory_attributes": [],
        "traces": []
    )},
     "ns3::V4Ping": dict{(
        "category": "Application",
        "create_function": create_element,
        "help": "",
        "connector_types": ["node"],
        "allow_routes": False,
        "allow_addresses": False,
        "stop_function": stop_application,
        "start_function": start_application,
        "status_function": status_application,
        "box_attributes": ["Remote",
            "Verbose",
            "Interval",
            "Size",
            "StartTime",
            "StopTime"],
        "factory_attributes": [],
        "traces": []
    )},
     "ns3::dot11s::PeerLink": dict{(
        "category": "",
        "create_function": create_element,
        "help": "",
        "connector_types": [],
        "allow_routes": False,
        "allow_addresses": False,
        "stop_function": None,
        "start_function": None,
        "status_function": None,
        "box_attributes": ["RetryTimeout",
            "HoldingTimeout",
            "ConfirmTimeout",
            "MaxRetries",
            "MaxBeaconLoss",
            "MaxPacketFailure"],
        "factory_attributes": [],
        "traces": []
    )},
     "ns3::PointToPointNetDevice": dict{(
        "category": "Device",
        "create_function": create_device,
        "help": "",
        "connector_types": ["node", "err", "queue", "chan"],
        "allow_routes": False,
        "allow_addresses": True,
        "stop_function": None,
        "start_function": None,
        "status_function": None,
        "box_attributes": ["Mtu",
            "Address",
            "DataRate",
            "InterframeGap"],
        "factory_attributes": [],
        "traces": ["p2ppcap"]
    )},
     "ns3::NakagamiPropagationLossModel": dict{(
        "category": "Loss",
        "create_function": create_element,
        "help": "",
        "connector_types": [],
        "allow_routes": False,
        "allow_addresses": False,
        "stop_function": None,
        "start_function": None,
        "status_function": None,
        "box_attributes": ["Distance1",
            "Distance2",
            "m0",
            "m1",
            "m2"],
        "factory_attributes": [],
        "traces": []
    )},
     "ns3::AarfWifiManager": dict{(
        "category": "Manager",
        "create_function": create_element,
        "help": "",
        "connector_types": ["dev"],
        "allow_routes": False,
        "allow_addresses": False,
        "stop_function": None,
        "start_function": None,
        "status_function": None,
        "box_attributes": ["SuccessK",
            "TimerK",
            "MaxSuccessThreshold",
            "MinTimerThreshold",
            "MinSuccessThreshold",
            "IsLowLatency",
            "MaxSsrc",
            "MaxSlrc",
            "RtsCtsThreshold",
            "FragmentationThreshold",
            "NonUnicastMode"],
        "factory_attributes": [],
        "traces": []
    )},
     "ns3::Ipv6OptionJumbogram": dict{(
        "category": "",
        "create_function": create_element,
        "help": "",
        "connector_types": [],
        "allow_routes": False,
        "allow_addresses": False,
        "stop_function": None,
        "start_function": None,
        "status_function": None,
        "box_attributes": ["OptionNumber"],
        "factory_attributes": [],
        "traces": []
    )},
     "ns3::TwoRayGroundPropagationLossModel": dict{(
        "category": "Loss",
        "create_function": create_element,
        "help": "",
        "connector_types": [],
        "allow_routes": False,
        "allow_addresses": False,
        "stop_function": None,
        "start_function": None,
        "status_function": None,
        "box_attributes": ["Lambda",
            "SystemLoss",
            "MinDistance",
            "HeightAboveZ"],
        "factory_attributes": [],
        "traces": []
    )},
     "ns3::OnOffApplication": dict{(
        "category": "Application",
        "create_function": create_element,
        "help": "",
        "connector_types": ["node"],
        "allow_routes": False,
        "allow_addresses": False,
        "stop_function": stop_application,
        "start_function": start_application,
        "status_function": status_application,
        "box_attributes": ["DataRate",
            "PacketSize",
            "Remote",
            "OnTime",
            "OffTime",
            "MaxBytes",
            "Protocol",
            "StartTime",
            "StopTime"],
        "factory_attributes": [],
        "traces": []
    )},
     "ns3::AdhocWifiMac": dict{(
        "category": "Mac",
        "create_function": create_element,
        "help": "",
        "connector_types": [],
        "allow_routes": False,
        "allow_addresses": False,
        "stop_function": None,
        "start_function": None,
        "status_function": None,
        "box_attributes": ["CtsTimeout",
            "AckTimeout",
            "BasicBlockAckTimeout",
            "CompressedBlockAckTimeout",
            "Sifs",
            "EifsNoDifs",
            "Slot",
            "Pifs",
            "MaxPropagationDelay",
            "Ssid"],
        "factory_attributes": [],
        "traces": []
    )},
     "ns3::ConstantAccelerationMobilityModel": dict{(
        "category": "Mobility",
        "create_function": create_element,
        "help": "",
        "connector_types": ["node"],
        "allow_routes": False,
        "allow_addresses": False,
        "stop_function": None,
        "start_function": None,
        "status_function": None,
        "box_attributes": ["Position",
            "Velocity"],
        "factory_attributes": [],
        "traces": []
    )},
     "ns3::GaussMarkovMobilityModel": dict{(
        "category": "Mobility",
        "create_function": create_element,
        "help": "",
        "connector_types": ["node"],
        "allow_routes": False,
        "allow_addresses": False,
        "stop_function": None,
        "start_function": None,
        "status_function": None,
        "box_attributes": ["Bounds",
            "TimeStep",
            "Alpha",
            "MeanVelocity",
            "MeanDirection",
            "MeanPitch",
            "NormalVelocity",
            "NormalDirection",
            "NormalPitch",
            "Position",
            "Velocity"],
        "factory_attributes": [],
        "traces": []
    )},
     "ns3::dot11s::HwmpProtocol": dict{(
        "category": "Protocol",
        "create_function": create_element,
        "help": "",
        "connector_types": ["node"]
        "allow_routes": False,
        "allow_addresses": False,
        "stop_function": None,
        "start_function": None,
        "status_function": None,
        "box_attributes": ["RandomStart",
            "MaxQueueSize",
            "Dot11MeshHWMPmaxPREQretries",
            "Dot11MeshHWMPnetDiameterTraversalTime",
            "Dot11MeshHWMPpreqMinInterval",
            "Dot11MeshHWMPperrMinInterval",
            "Dot11MeshHWMPactiveRootTimeout",
            "Dot11MeshHWMPactivePathTimeout",
            "Dot11MeshHWMPpathToRootInterval",
            "Dot11MeshHWMPrannInterval",
            "MaxTtl",
            "UnicastPerrThreshold",
            "UnicastPreqThreshold",
            "UnicastDataThreshold",
            "DoFlag",
            "RfFlag"],
        "factory_attributes": [],
        "traces": []
    )},
     "ns3::NscTcpL4Protocol": dict{(
        "category": "Protocol",
        "create_function": create_element,
        "help": "",
        "connector_types": ["node"],
        "allow_routes": False,
        "allow_addresses": False,
        "stop_function": None,
        "start_function": None,
        "status_function": None,
        "box_attributes": ["Library",
          "ProtocolNumber"],
        "factory_attributes": [],
        "traces": []
    )},
     "ns3::dot11s::AirtimeLinkMetricCalculator": dict{(
        "category": "",
        "create_function": create_element,
        "help": "",
        "connector_types": [],
        "allow_routes": False,
        "allow_addresses": False,
        "stop_function": None,
        "start_function": None,
        "status_function": None,
        "box_attributes": ["Dot11sMeshHeaderLength"],
        "factory_attributes": [],
        "traces": []
    )},
     "ns3::UanMacCw": dict{(
        "category": "",
        "create_function": create_element,
        "help": "",
        "connector_types": [],
        "allow_routes": False,
        "allow_addresses": False,
        "stop_function": None,
        "start_function": None,
        "status_function": None,
        "box_attributes": ["CW",
           "SlotTime"],
        "factory_attributes": [],
        "traces": []
    )},
     "ns3::AthstatsWifiTraceSink": dict{(
        "category": "",
        "create_function": create_element,
        "help": "",
        "connector_types": [],
        "allow_routes": False,
        "allow_addresses": False,
        "stop_function": None,
        "start_function": None,
        "status_function": None,
        "box_attributes": ["Interval"],
        "factory_attributes": [],
        "traces": []
    )},
     "ns3::FlameStack": dict{(
        "category": "",
        "create_function": create_element,
        "help": "",
        "connector_types": [],
        "allow_routes": False,
        "allow_addresses": False,
        "stop_function": None,
        "start_function": None,
        "status_function": None,
        "box_attributes": [],
        "factory_attributes": [],
        "traces": []
    )},
     "ns3::UanMacRc": dict{(
        "category": "",
        "create_function": create_element,
        "help": "",
        "connector_types": [],
        "allow_routes": False,
        "allow_addresses": False,
        "stop_function": None,
        "start_function": None,
        "status_function": None,
        "box_attributes": ["RetryRate",
            "MaxFrames",
            "QueueLimit",
            "SIFS",
            "NumberOfRates",
            "MinRetryRate",
            "RetryStep",
            "NumberOfRetryRates",
            "MaxPropDelay"],
        "factory_attributes": [],
        "traces": []
    )},
     "ns3::WaypointMobilityModel": dict{(
        "category": "Mobility",
        "create_function": create_element,
        "help": "",
        "connector_types": ["node"],
        "allow_routes": False,
        "allow_addresses": False,
        "stop_function": None,
        "start_function": None,
        "status_function": None,
        "box_attributes": ["WaypointsLeft",
            "Position",
            "Velocity"],
        "factory_attributes": [],
        "traces": []
    )},
     "ns3::FileDescriptorNetDevice": dict{(
        "category": "Device",
        "create_function": create_device,
        "help": "Network interface associated to a file descriptor",
        "connector_types": ["node", "fd", "err"],
        "allow_routes": False,
        "allow_addresses": True,
        "stop_function": None,
        "start_function": None,
        "status_function": None,
        "box_attributes": ["Address"],
        "factory_attributes": [],
        "traces": ["fdpcap"]
    )},
     "ns3::CsmaNetDevice": dict{(
        "category": "Device",
        "create_function": create_device,
        "help": "CSMA (carrier sense, multiple access) interface",
        "connector_types": ["node", "chan", "err", "queue"],
        "allow_routes": False,
        "allow_addresses": True,
        "stop_function": None,
        "start_function": None,
        "status_function": None,
        "box_attributes": ["Address",
            "Mtu",
            "SendEnable",
            "ReceiveEnable"],
        "factory_attributes": [],
        "traces": ["csmapcap", "csmapcap_promisc"]
    )},
     "ns3::UanPropModelThorp": dict{(
        "category": "",
        "create_function": create_element,
        "help": "",
        "connector_types": [],
        "allow_routes": False,
        "allow_addresses": False,
        "stop_function": None,
        "start_function": None,
        "status_function": None,
        "box_attributes": ["SpreadCoef"],
        "factory_attributes": [],
        "traces": []
    )},
     "ns3::NqstaWifiMac": dict{(
        "category": "Mac",
        "create_function": create_element,
        "help": "",
        "connector_types": [],
        "allow_routes": False,
        "allow_addresses": False,
        "stop_function": None,
        "start_function": None,
        "status_function": None,
        "box_attributes": ["ProbeRequestTimeout",
            "AssocRequestTimeout",
            "MaxMissedBeacons",
            "CtsTimeout",
            "AckTimeout",
            "BasicBlockAckTimeout",
            "CompressedBlockAckTimeout",
            "Sifs",
            "EifsNoDifs",
            "Slot",
            "Pifs",
            "MaxPropagationDelay",
            "Ssid"],
        "factory_attributes": [],
        "traces": []
    )},
     "ns3::Icmpv6L4Protocol": dict{(
        "category": "Protocol",
        "create_function": create_element,
        "help": "",
        "connector_types": ["node"],
        "allow_routes": False,
        "allow_addresses": False,
        "stop_function": None,
        "start_function": None,
        "status_function": None,
        "box_attributes": ["DAD",
            "ProtocolNumber"],
        "factory_attributes": [],
        "traces": []
    )},
     "ns3::SimpleNetDevice": dict{(
        "category": "Device",
        "create_function": create_device,
        "help": "",
        "connector_types": ["node", "chan"],
        "allow_routes": False,
        "allow_addresses": True,
        "stop_function": None,
        "start_function": None,
        "status_function": None,
        "box_attributes": [],
        "factory_attributes": [],
        "traces": []
    )},
     "ns3::FriisPropagationLossModel": dict{(
        "category": "Loss",
        "create_function": create_element,
        "help": "",
        "connector_types": [],
        "allow_routes": False,
        "allow_addresses": False,
        "stop_function": None,
        "start_function": None,
        "status_function": None,
        "box_attributes": ["Lambda",
            "SystemLoss",
            "MinDistance"],
        "factory_attributes": [],
        "traces": []
    )},
     "ns3::Ipv6OptionRouterAlert": dict{(
        "category": "",
        "create_function": create_element,
        "help": "",
        "connector_types": [],
        "allow_routes": False,
        "allow_addresses": False,
        "stop_function": None,
        "start_function": None,
        "status_function": None,
        "box_attributes": ["OptionNumber"],
        "factory_attributes": [],
        "traces": []
    )},
     "ns3::UniformDiscPositionAllocator": dict{(
        "category": "Mobility",
        "create_function": create_element,
        "help": "",
        "connector_types": [],
        "allow_routes": False,
        "allow_addresses": False,
        "stop_function": None,
        "start_function": None,
        "status_function": None,
        "box_attributes": ["rho",
            "X",
            "Y"],
        "factory_attributes": [],
        "traces": []
    )},
     "ns3::RandomBoxPositionAllocator": dict{(
        "category": "Mobility",
        "create_function": create_element,
        "help": "",
        "connector_types": ["node"],
        "allow_routes": False,
        "allow_addresses": False,
        "stop_function": None,
        "start_function": None,
        "status_function": None,
        "box_attributes": ["X",
            "Y",
            "Z"],
        "factory_attributes": [],
        "traces": []
    )},
     "ns3::Ipv6ExtensionDestination": dict{(
        "category": "",
        "create_function": create_element,
        "help": "",
        "connector_types": [],
        "allow_routes": False,
        "allow_addresses": False,
        "stop_function": None,
        "start_function": None,
        "status_function": None,
        "box_attributes": ["ExtensionNumber"],
        "factory_attributes": [],
        "traces": []
    )},
     "ns3::LoopbackNetDevice": dict{(
        "category": "Device",
        "create_function": create_device,
        "help": "",
        "connector_types": ["node"],
        "allow_routes": False,
        "allow_addresses": False,
        "stop_function": None,
        "start_function": None,
        "status_function": None,
        "box_attributes": [],
        "factory_attributes": [],
        "traces": []
    )},
     "ns3::ConstantSpeedPropagationDelayModel": dict{(
        "category": "Delay",
        "create_function": create_element,
        "help": "",
        "connector_types": ["chan"],
        "allow_routes": False,
        "allow_addresses": False,
        "stop_function": None,
        "start_function": None,
        "status_function": None,
        "box_attributes": ["Speed"],
        "factory_attributes": [],
        "traces": []
    )},
     "ns3::Ipv6ExtensionHopByHop": dict{(
        "category": "",
        "create_function": create_element,
        "help": "",
        "connector_types": [],
        "allow_routes": False,
        "allow_addresses": False,
        "stop_function": None,
        "start_function": None,
        "status_function": None,
        "box_attributes": ["ExtensionNumber"],
        "factory_attributes": [],
        "traces": []
    )},
     "ns3::BridgeChannel": dict{(
        "category": "Channel",
        "create_function": create_element,
        "help": "",
        "connector_types": ["devs"],
        "allow_routes": False,
        "allow_addresses": False,
        "stop_function": None,
        "start_function": None,
        "status_function": None,
        "box_attributes": [],
        "factory_attributes": [],
        "traces": []
    )},
     "ns3::Radvd": dict{(
        "category": "",
        "create_function": create_element,
        "help": "",
        "connector_types": [],
        "allow_routes": False,
        "allow_addresses": False,
        "stop_function": None,
        "start_function": None,
        "status_function": None,
        "box_attributes": ["StartTime",
            "StopTime"],
        "factory_attributes": [],
        "traces": []
    )},
     "ns3::PacketSocket": dict{(
        "category": "",
        "create_function": create_element,
        "help": "",
        "connector_types": [],
        "allow_routes": False,
        "allow_addresses": False,
        "stop_function": None,
        "start_function": None,
        "status_function": None,
        "box_attributes": ["RcvBufSize"],
        "factory_attributes": [],
        "traces": []
    )},
     "ns3::flame::FlameProtocol": dict{(
        "category": "Protocol",
        "create_function": create_element,
        "help": "",
        "connector_types": ["node"],
        "allow_routes": False,
        "allow_addresses": False,
        "stop_function": None,
        "start_function": None,
        "status_function": None,
        "box_attributes": ["BroadcastInterval",
            "MaxCost"],
        "factory_attributes": [],
        "traces": []
    )},
     "ns3::Cost231PropagationLossModel": dict{(
        "category": "Loss",
        "create_function": create_element,
        "help": "",
        "connector_types": [],
        "allow_routes": False,
        "allow_addresses": False,
        "stop_function": None,
        "start_function": None,
        "status_function": None,
        "box_attributes": ["Lambda",
            "Frequency",
            "BSAntennaHeight",
            "SSAntennaHeight",
            "MinDistance"],
        "factory_attributes": [],
        "traces": []
    )},
     "ns3::Ipv6ExtensionESP": dict{(
        "category": "",
        "create_function": create_element,
        "help": "",
        "connector_types": [],
        "allow_routes": False,
        "allow_addresses": False,
        "stop_function": None,
        "start_function": None,
        "status_function": None,
        "box_attributes": ["ExtensionNumber"],
        "factory_attributes": [],
        "traces": []
    )},
     "ns3::CaraWifiManager": dict{(
        "category": "Manager",
        "create_function": create_element,
        "help": "",
        "connector_types": ["dev"],
        "allow_routes": False,
        "allow_addresses": False,
        "stop_function": None,
        "start_function": None,
        "status_function": None,
        "box_attributes": ["ProbeThreshold",
            "FailureThreshold",
            "SuccessThreshold",
            "Timeout",
            "IsLowLatency",
            "MaxSsrc",
            "MaxSlrc",
            "RtsCtsThreshold",
            "FragmentationThreshold",
            "NonUnicastMode"],
            "factory_attributes": [],
        "traces": []
    )},
     "ns3::RttMeanDeviation": dict{(
        "category": "",
        "create_function": create_element,
        "help": "",
        "connector_types": [],
        "allow_routes": False,
        "allow_addresses": False,
        "stop_function": None,
        "start_function": None,
        "status_function": None,
        "box_attributes": ["Gain",
            "MaxMultiplier",
            "InitialEstimation",
            "MinRTO"],
        "factory_attributes": [],
        "traces": []
    )},
     "ns3::Icmpv4L4Protocol": dict{(
        "category": "Protocol",
        "create_function": create_element,
        "help": "",
        "connector_types": ["node"],
        "allow_routes": False,
        "allow_addresses": False,
        "stop_function": None,
        "start_function": None,
        "status_function": None,
        "box_attributes": ["ProtocolNumber"],
        "factory_attributes": [],
        "traces": []
    )},
     "ns3::WaveformGenerator": dict{(
        "category": "",
        "create_function": create_element,
        "help": "",
        "connector_types": [],
        "allow_routes": False,
        "allow_addresses": False,
        "stop_function": None,
        "start_function": None,
        "status_function": None,
        "box_attributes": ["Period",
            "DutyCycle"],
        "factory_attributes": [],
        "traces": []
    )},
     "ns3::YansWifiChannel": dict{(
        "category": "Channel",
        "create_function": create_element,
        "help": "",
        "connector_types": ["phys", "delay", "loss"],
        "allow_routes": False,
        "allow_addresses": False,
        "stop_function": None,
        "start_function": None,
        "status_function": None,
        "box_attributes": [],
        "factory_attributes": [],
        "traces": []
    )},
     "ns3::SimpleChannel": dict{(
        "category": "Channel",
        "create_function": create_element,
        "help": "",
        "connector_types": ["devs"],
        "allow_routes": False,
        "allow_addresses": False,
        "stop_function": None,
        "start_function": None,
        "status_function": None,
        "box_attributes": [],
        "factory_attributes": [],
        "traces": []
    )},
     "ns3::Ipv6ExtensionFragment": dict{(
        "category": "",
        "create_function": create_element,
        "help": "",
        "connector_types": [],
        "allow_routes": False,
        "allow_addresses": False,
        "stop_function": None,
        "start_function": None,
        "status_function": None,
        "box_attributes": ["ExtensionNumber"],
        "factory_attributes": [],
        "traces": []
    )},
     "ns3::Dot11sStack": dict{(
        "category": "",
        "create_function": create_element,
        "help": "",
        "connector_types": [],
        "allow_routes": False,
        "allow_addresses": False,
        "stop_function": None,
        "start_function": None,
        "status_function": None,
        "box_attributes": ["Root"],
        "factory_attributes": [],
        "traces": []
    )},
     "ns3::FriisSpectrumPropagationLossModel": dict{(
        "category": "Loss",
        "create_function": create_element,
        "help": "",
        "connector_types": [],
        "allow_routes": False,
        "allow_addresses": False,
        "stop_function": None,
        "start_function": None,
        "status_function": None,
        "box_attributes": [],
        "factory_attributes": [],
        "traces": []
    )},
     "ns3::RandomRectanglePositionAllocator": dict{(
        "category": "Mobility",
        "create_function": create_element,
        "help": "",
        "connector_types": [],
        "allow_routes": False,
        "allow_addresses": False,
        "stop_function": None,
        "start_function": None,
        "status_function": None,
        "box_attributes": ["X",
           "Y"],
        "factory_attributes": [],
        "traces": []
    )},
     "ns3::NqapWifiMac": dict{(
        "category": "",
        "create_function": create_element,
        "help": "",
        "connector_types": [],
        "allow_routes": False,
        "allow_addresses": False,
        "stop_function": None,
        "start_function": None,
        "status_function": None,
        "box_attributes": ["BeaconInterval",
            "BeaconGeneration",
            "CtsTimeout",
            "AckTimeout",
            "BasicBlockAckTimeout",
            "CompressedBlockAckTimeout",
            "Sifs",
            "EifsNoDifs",
            "Slot",
            "Pifs",
            "MaxPropagationDelay",
            "Ssid"],
        "factory_attributes": [],
        "traces": []
    )},
     "ns3::HierarchicalMobilityModel": dict{(
        "category": "Mobility",
        "create_function": create_element,
        "help": "",
        "connector_types": ["node"],
        "allow_routes": False,
        "allow_addresses": False,
        "stop_function": None,
        "start_function": None,
        "status_function": None,
        "box_attributes": ["Position",
            "Velocity"],
        "factory_attributes": [],
        "traces": []
    )},
     "ns3::ThreeLogDistancePropagationLossModel": dict{(
        "category": "Loss",
        "create_function": create_element,
        "help": "",
        "connector_types": ["prev", "next"],
        "allow_routes": False,
        "allow_addresses": False,
        "stop_function": None,
        "start_function": None,
        "status_function": None,
        "box_attributes": ["Distance0",
            "Distance1",
            "Distance2",
            "Exponent0",
            "Exponent1",
            "Exponent2",
            "ReferenceLoss"],
        "factory_attributes": [],
        "traces": []
    )},
     "ns3::UanNoiseModelDefault": dict{(
        "category": "",
        "create_function": create_element,
        "help": "",
        "connector_types": [],
        "allow_routes": False,
        "allow_addresses": False,
        "stop_function": None,
        "start_function": None,
        "status_function": None,
        "box_attributes": ["Wind",
            "Shipping"],
        "factory_attributes": [],
        "traces": []
    )},
     "ns3::dot11s::HwmpRtable": dict{(
        "category": "",
        "create_function": create_element,
        "help": "",
        "connector_types": [],
        "allow_routes": False,
        "allow_addresses": False,
        "stop_function": None,
        "start_function": None,
        "status_function": None,
        "box_attributes": [],
        "factory_attributes": [],
        "traces": []
    )},
     "ns3::PacketBurst": dict{(
        "category": "",
        "create_function": create_element,
        "help": "",
        "connector_types": [],
        "allow_routes": False,
        "allow_addresses": False,
        "stop_function": None,
        "start_function": None,
        "status_function": None,
        "box_attributes": [],
        "factory_attributes": [],
        "traces": []
    )},
     "ns3::RandomPropagationDelayModel": dict{(
        "category": "Delay",
        "create_function": create_element,
        "help": "",
        "connector_types": ["chan"],
        "allow_routes": False,
        "allow_addresses": False,
        "stop_function": None,
        "start_function": None,
        "status_function": None,
        "box_attributes": ["Variable"],
        "factory_attributes": [],
        "traces": []
    )},
     "ns3::ArpL3Protocol": dict{(
        "category": "Protocol",
        "create_function": create_element,
        "help": "",
        "connector_types": ["node"],
        "allow_routes": False,
        "allow_addresses": False,
        "stop_function": None,
        "start_function": None,
        "status_function": None,
        "box_attributes": [],
        "factory_attributes": [],
        "traces": []
    )},
     "ns3::SteadyStateRandomWaypointMobilityModel": dict{(
        "category": "Mobility",
        "create_function": create_element,
        "help": "",
        "connector_types": ["node"],
        "allow_routes": False,
        "allow_addresses": False,
        "stop_function": None,
        "start_function": None,
        "status_function": None,
        "box_attributes": ["MinSpeed",
            "MaxSpeed",
            "MinPause",
            "MaxPause",
            "MinX",
            "MaxX",
            "MinY",
            "MaxY",
            "Position",
            "Velocity"],
        "factory_attributes": [],
        "traces": []
    )},
     "ns3::BaseStationNetDevice": dict{(
        "category": "Device",
        "create_function": create_device,
        "help": "",
        "connector_types": ["node"],
        "allow_routes": False,
        "allow_addresses": True,
        "stop_function": None,
        "start_function": None,
        "status_function": None,
        "box_attributes": ["InitialRangInterval",
            "DcdInterval",
            "UcdInterval",
            "IntervalT8",
            "RangReqOppSize",
            "BwReqOppSize",
            "MaxRangCorrectionRetries",
            "Mtu",
            "RTG",
            "TTG"],
        "factory_attributes": [],
        "traces": []
    )},
     "ns3::UdpServer": dict{(
        "category": "Application",
        "create_function": create_element,
        "help": "",
        "connector_types": ["node"],
        "allow_routes": False,
        "allow_addresses": False,
        "stop_function": stop_application,
        "start_function": start_application,
        "status_function": status_application,
        "box_attributes": ["Port",
            "PacketWindowSize",
            "StartTime",
            "StopTime"],
        "factory_attributes": [],
        "traces": []
    )},
     "ns3::AarfcdWifiManager": dict{(
        "category": "Manager",
        "create_function": create_element,
        "help": "",
        "connector_types": ["dev"],
        "allow_routes": False,
        "allow_addresses": False,
        "stop_function": None,
        "start_function": None,
        "status_function": None,
        "box_attributes": ["SuccessK",
            "TimerK",
            "MaxSuccessThreshold",
            "MinTimerThreshold",
            "MinSuccessThreshold",
            "MinRtsWnd",
            "MaxRtsWnd",
            "TurnOffRtsAfterRateDecrease",
            "TurnOnRtsAfterRateIncrease",
            "IsLowLatency",
            "MaxSsrc",
            "MaxSlrc",
            "RtsCtsThreshold",
            "FragmentationThreshold",
            "NonUnicastMode"],
        "factory_attributes": [],
        "traces": []
    )},
     "ns3::UanTransducerHd": dict{(
        "category": "",
        "create_function": create_element,
        "help": "",
        "connector_types": [],
        "allow_routes": False,
        "allow_addresses": False,
        "stop_function": None,
        "start_function": None,
        "status_function": None,
        "box_attributes": [],
        "factory_attributes": [],
        "traces": []
    )},
     "ns3::LogDistancePropagationLossModel": dict{(
        "category": "Loss",
        "create_function": create_element,
        "help": "",
        "connector_types": ["prev", "next"],
        "allow_routes": False,
        "allow_addresses": False,
        "stop_function": None,
        "start_function": None,
        "status_function": None,
        "box_attributes": ["Exponent",
            "ReferenceDistance",
            "ReferenceLoss"],
        "factory_attributes": [],
        "traces": []
    )},
     "ns3::EmuNetDevice": dict{(
        "category": "Device",
        "create_function": create_device,
        "help": "",
        "connector_types": ["node", "queue"],
        "allow_routes": False,
        "allow_addresses": False,
        "stop_function": None,
        "start_function": None,
        "status_function": None,
        "box_attributes": ["Mtu",
            "Address",
            "DeviceName",
            "Start",
            "Stop",
            "RxQueueSize"],
        "factory_attributes": [],
        "traces": []
    )},
     "ns3::Ipv6ExtensionLooseRouting": dict{(
        "category": "",
        "create_function": create_element,
        "help": "",
        "connector_types": [],
        "allow_routes": False,
        "allow_addresses": False,
        "stop_function": None,
        "start_function": None,
        "status_function": None,
        "box_attributes": ["ExtensionNumber"],
        "factory_attributes": [],
        "traces": []
    )},
     "ns3::RandomWaypointMobilityModel": dict{(
        "category": "Mobility",
        "create_function": create_element,
        "help": "",
        "connector_types": ["node"],
        "allow_routes": False,
        "allow_addresses": False,
        "stop_function": None,
        "start_function": None,
        "status_function": None,
        "box_attributes": ["Speed",
            "Pause",
            "Position",
            "Velocity"],
        "factory_attributes": [],
        "traces": []
    )},
     "ns3::RangePropagationLossModel": dict{(
        "category": "",
        "create_function": create_element,
        "help": "",
        "connector_types": [],
        "allow_routes": False,
        "allow_addresses": False,
        "stop_function": None,
        "start_function": None,
        "status_function": None,
        "box_attributes": ["MaxRange"],
        "factory_attributes": [],
        "traces": []
    )},
     "ns3::AlohaNoackNetDevice": dict{(
        "category": "Device",
        "create_function": create_element,
        "help": "",
        "connector_types": ["node"],
        "allow_routes": False,
        "allow_addresses": True,
        "stop_function": None,
        "start_function": None,
        "status_function": None,
        "box_attributes": ["Address",
            "Mtu"],
        "factory_attributes": [],
        "traces": []
    )},
     "ns3::MatrixPropagationLossModel": dict{(
        "category": "Loss",
        "create_function": create_element,
        "help": "",
        "connector_types": [],
        "allow_routes": False,
        "allow_addresses": False,
        "stop_function": None,
        "start_function": None,
        "status_function": None,
        "box_attributes": ["DefaultLoss"],
        "factory_attributes": [],
        "traces": []
    )},
     "ns3::WifiNetDevice": dict{(
        "category": "Device",
        "create_function": create_device,
        "help": "",
        "connector_types": ["node", "mac", "phy", "manager"],
        "allow_routes": False,
        "allow_addresses": True,
        "stop_function": None,
        "start_function": None,
        "status_function": None,
        "box_attributes": ["Mtu"],
        "factory_attributes": [],
        "traces": []
    )},
     "ns3::CsmaChannel": dict{(
        "category": "Channel",
        "create_function": create_element,
        "help": "",
        "connector_types": ["devs"],
        "allow_routes": False,
        "allow_addresses": False,
        "stop_function": None,
        "start_function": None,
        "status_function": None,
        "box_attributes": ["DataRate",
            "Delay"],
        "factory_attributes": [],
        "traces": []
    )},
     "ns3::BridgeNetDevice": dict{(
        "category": "Device",
        "create_function": create_device,
        "help": "",
        "connector_types": ["node"],
        "allow_routes": False,
        "allow_addresses": True,
        "stop_function": None,
        "start_function": None,
        "status_function": None,
        "box_attributes": ["Mtu",
           "EnableLearning",
           "ExpirationTime"],
        "factory_attributes": [],
        "traces": []
    )},
     "ns3::Ipv6ExtensionRouting": dict{(
        "category": "",
        "create_function": create_element,
        "help": "",
        "connector_types": [],
        "allow_routes": False,
        "allow_addresses": False,
        "stop_function": None,
        "start_function": None,
        "status_function": None,
        "box_attributes": ["ExtensionNumber"],
        "factory_attributes": [],
        "traces": []
    )},
     "ns3::QstaWifiMac": dict{(
        "category": "Mac",
        "create_function": create_wifi_standard_model,
        "help": "Station Wifi MAC Model",
        "connector_types": ["dev"],
        "allow_routes": False,
        "allow_addresses": False,
        "stop_function": None,
        "start_function": None,
        "status_function": None,
        "box_attributes": ["ProbeRequestTimeout",
            "AssocRequestTimeout",
            "MaxMissedBeacons",
            "CtsTimeout",
            "AckTimeout",
            "BasicBlockAckTimeout",
            "CompressedBlockAckTimeout",
            "Sifs",
            "EifsNoDifs",
            "Slot",
            "Pifs",
            "MaxPropagationDelay",
            "Ssid"],
        "factory_attributes": [],
        "traces": []
    )},
     "ns3::UdpEchoClient": dict{(
        "category": "Application",
        "create_function": create_element,
        "help": "",
        "connector_types": ["node"],
        "allow_routes": False,
        "allow_addresses": False,
        "stop_function": stop_application,
        "start_function": start_application,
        "status_function": status_application,
        "box_attributes": ["MaxPackets",
            "Interval",
            "RemoteAddress",
            "RemotePort",
            "PacketSize",
            "StartTime",
            "StopTime"],
        "factory_attributes": [],
        "traces": []
    )},
     "ns3::UdpClient": dict{(
        "category": "Application",
        "create_function": create_element,
        "help": "",
        "connector_types": ["node"],
        "allow_routes": False,
        "allow_addresses": False,
        "stop_function": stop_application,
        "start_function": start_application,
        "status_function": status_application,
        "box_attributes": ["MaxPackets",
            "Interval",
            "RemoteAddress",
            "RemotePort",
            "PacketSize",
            "StartTime",
            "StopTime"],
        "factory_attributes": [],
        "traces": []
    )},
     "ns3::PointToPointChannel": dict{(
        "category": "Channel",
        "create_function": create_element,
        "help": "",
        "connector_types": ["dev2"],
        "allow_routes": False,
        "allow_addresses": False,
        "stop_function": None,
        "start_function": None,
        "status_function": None,
        "box_attributes": ["Delay"],
        "factory_attributes": [],
        "traces": []
    )},
     "ns3::Ipv6StaticRouting": dict{(
        "category": "",
        "create_function": create_element,
        "help": "",
        "connector_types": [],
        "allow_routes": False,
        "allow_addresses": False,
        "stop_function": None,
        "start_function": None,
        "status_function": None,
        "box_attributes": [],
        "factory_attributes": [],
        "traces": []
    )},
     "ns3::DropTailQueue": dict{(
        "category": "Device",
        "create_function": create_element,
        "help": "",
        "connector_types": ["dev"],
        "allow_routes": False,
        "allow_addresses": False,
        "stop_function": None,
        "start_function": None,
        "status_function": None,
        "box_attributes": ["MaxPackets",
           "MaxBytes"],
        "factory_attributes": [],
        "traces": []
    )},
     "ns3::ConstantPositionMobilityModel": dict{(
        "category": "Mobility",
        "create_function": create_element,
        "help": "",
        "connector_types": ["node"],
        "allow_routes": False,
        "allow_addresses": False,
        "stop_function": None,
        "start_function": None,
        "status_function": None,
        "box_attributes": ["Position",
            "Velocity"],
        "factory_attributes": [],
        "traces": []
    )},
     "ns3::FixedRssLossModel": dict{(
        "category": "Loss",
        "create_function": create_element,
        "help": "",
        "connector_types": [],
        "allow_routes": False,
        "allow_addresses": False,
        "stop_function": None,
        "start_function": None,
        "status_function": None,
        "box_attributes": ["Rss"],
        "factory_attributes": [],
        "traces": []
    )},
     "ns3::EnergySourceContainer": dict{(
        "category": "",
        "create_function": create_element,
        "help": "",
        "connector_types": [],
        "allow_routes": False,
        "allow_addresses": False,
        "stop_function": None,
        "start_function": None,
        "status_function": None,
        "box_attributes": [],
        "factory_attributes": [],
        "traces": []
    )},
     "ns3::RandomWalk2dMobilityModel": dict{(
        "category": "Mobility",
        "create_function": create_element,
        "help": "",
        "connector_types": ["node"],
        "allow_routes": False,
        "allow_addresses": False,
        "stop_function": None,
        "start_function": None,
        "status_function": None,
        "box_attributes": ["Bounds",
            "Time",
            "Distance",
            "Mode",
            "Direction",
            "Speed",
            "Position",
            "Velocity"],
        "factory_attributes": [],
        "traces": []
    )},
     "ns3::ListPositionAllocator": dict{(
        "category": "",
        "create_function": create_element,
        "help": "",
        "connector_types": [],
        "allow_routes": False,
        "allow_addresses": False,
        "stop_function": None,
        "start_function": None,
        "status_function": None,
        "box_attributes": [],
        "factory_attributes": [],
        "traces": []
    )},
     "ns3::dot11s::PeerManagementProtocol": dict{(
        "category": "Protocol",
        "create_function": create_element,
        "help": "",
        "connector_types": ["node"],
        "allow_routes": False,
        "allow_addresses": False,
        "stop_function": None,
        "start_function": None,
        "status_function": None,
        "box_attributes": ["MaxNumberOfPeerLinks",
            "MaxBeaconShiftValue",
            "EnableBeaconCollisionAvoidance"],
        "factory_attributes": [],
        "traces": []
    )},
     "ns3::MeshPointDevice": dict{(
        "category": "Device",
        "create_function": create_device,
        "help": "",
        "connector_types": ["node"],
        "allow_routes": False,
        "allow_addresses": True,
        "stop_function": None,
        "start_function": None,
        "status_function": None,
        "box_attributes": ["Mtu"],
        "factory_attributes": [],
        "traces": []
    )},
     "ns3::BasicEnergySource": dict{(
        "category": "",
        "create_function": create_element,
        "help": "",
        "connector_types": [],
        "allow_routes": False,
        "allow_addresses": False,
        "stop_function": None,
        "start_function": None,
        "status_function": None,
        "box_attributes": ["BasicEnergySourceInitialEnergyJ",
            "BasicEnergySupplyVoltageV",
            "PeriodicEnergyUpdateInterval"],
        "factory_attributes": [],
        "traces": []
    )},
     "ns3::Ipv6OptionPadn": dict{(
        "category": "",
        "create_function": create_element,
        "help": "",
        "connector_types": [],
        "allow_routes": False,
        "allow_addresses": False,
        "stop_function": None,
        "start_function": None,
        "status_function": None,
        "box_attributes": ["OptionNumber"],
        "factory_attributes": [],
        "traces": []
    )},
     "ns3::QapWifiMac": dict{(
        "category": "Mac",
        "create_function": create_wifi_standard_model,
        "help": "Access point Wifi MAC Model",
        "connector_types": ["dev"],
        "allow_routes": False,
        "allow_addresses": False,
        "stop_function": None,
        "start_function": None,
        "status_function": None,
        "box_attributes": ["BeaconInterval",
            "BeaconGeneration",
            "CtsTimeout",
            "AckTimeout",
            "BasicBlockAckTimeout",
            "CompressedBlockAckTimeout",
            "Sifs",
            "EifsNoDifs",
            "Slot",
            "Pifs",
            "MaxPropagationDelay",
            "Ssid"],
        "factory_attributes": [],
        "traces": []
    )},
     "ns3::YansErrorRateModel": dict{(
        "category": "Error",
        "create_function": create_element,
        "help": "",
        "connector_types": [],
        "allow_routes": False,
        "allow_addresses": False,
        "stop_function": None,
        "start_function": None,
        "status_function": None,
        "box_attributes": [],
        "factory_attributes": [],
        "traces": []
    )},
     "ns3::WifiMacQueue": dict{(
        "category": "",
        "create_function": create_element,
        "help": "",
        "connector_types": [],
        "allow_routes": False,
        "allow_addresses": False,
        "stop_function": None,
        "start_function": None,
        "status_function": None,
        "box_attributes": ["MaxPacketNumber",
           "MaxDelay"],
        "factory_attributes": [],
        "traces": []
    )},
     "ns3::NonCommunicatingNetDevice": dict{(
        "category": "Device",
        "create_function": create_device,
        "help": "",
        "connector_types": ["node"],
        "allow_routes": False,
        "allow_addresses": True,
        "stop_function": None,
        "start_function": None,
        "status_function": None,
        "box_attributes": [],
        "factory_attributes": [],
        "traces": []
    )},
     "ns3::RateErrorModel": dict{(
        "category": "Error",
        "create_function": create_element,
        "help": "",
        "connector_types": [],
        "allow_routes": False,
        "allow_addresses": False,
        "stop_function": None,
        "start_function": None,
        "status_function": None,
        "box_attributes": ["ErrorUnit",
            "ErrorRate",
            "RanVar",
            "IsEnabled"],
        "factory_attributes": [],
        "traces": []
    )},
     "ns3::MeshWifiInterfaceMac": dict{(
        "category": "",
        "create_function": create_element,
        "help": "",
        "connector_types": [],
        "allow_routes": False,
        "allow_addresses": False,
        "stop_function": None,
        "start_function": None,
        "status_function": None,
        "box_attributes": ["BeaconInterval",
            "RandomStart",
            "BeaconGeneration",
            "CtsTimeout",
            "AckTimeout",
            "BasicBlockAckTimeout",
            "CompressedBlockAckTimeout",
            "Sifs",
            "EifsNoDifs",
            "Slot",
            "Pifs",
            "MaxPropagationDelay",
            "Ssid"],
        "factory_attributes": [],
        "traces": []
    )},
     "ns3::UanPhyCalcSinrDual": dict{(
        "category": "",
        "create_function": create_element,
        "help": "",
        "connector_types": [],
        "allow_routes": False,
        "allow_addresses": False,
        "stop_function": None,
        "start_function": None,
        "status_function": None,
        "box_attributes": [],
        "factory_attributes": [],
        "traces": []
    )},
     "ns3::Ipv6ExtensionAH": dict{(
        "category": "",
        "create_function": create_element,
        "help": "",
        "connector_types": [],
        "allow_routes": False,
        "allow_addresses": False,
        "stop_function": None,
        "start_function": None,
        "status_function": None,
        "box_attributes": ["ExtensionNumber"],
        "factory_attributes": [],
        "traces": []
    )},
     "ns3::SingleModelSpectrumChannel": dict{(
        "category": "Channel",
        "create_function": create_element,
        "help": "",
        "connector_types": [],
        "allow_routes": False,
        "allow_addresses": False,
        "stop_function": None,
        "start_function": None,
        "status_function": None,
        "box_attributes": [],
        "factory_attributes": [],
        "traces": []
    )},
     "ns3::YansWifiPhy": dict{(
        "category": "Phy",
        "create_function": create_element,
        "help": "",
        "connector_types": ["dev", "err", "chan"],
        "allow_routes": False,
        "allow_addresses": False,
        "stop_function": None,
        "start_function": None,
        "status_function": None,
        "box_attributes": ["EnergyDetectionThreshold",
            "CcaMode1Threshold",
            "TxGain",
            "RxGain",
            "TxPowerLevels",
            "TxPowerEnd",
            "TxPowerStart",
            "RxNoiseFigure",
            "ChannelSwitchDelay",
            "ChannelNumber"],
        "factory_attributes": [],
        "traces": ["yanswifipcap"]
    )},
     "ns3::WifiRadioEnergyModel": dict{(
        "category": "",
        "create_function": create_element,
        "help": "",
        "connector_types": [],
        "allow_routes": False,
        "allow_addresses": False,
        "stop_function": None,
        "start_function": None,
        "status_function": None,
        "box_attributes": ["TxCurrentA",
            "RxCurrentA",
            "IdleCurrentA",
            "SleepCurrentA"],
        "factory_attributes": [],
        "traces": []
    )},
     "ns3::EdcaTxopN": dict{(
        "category": "",
        "create_function": create_element,
        "help": "",
        "connector_types": [],
        "allow_routes": False,
        "allow_addresses": False,
        "stop_function": None,
        "start_function": None,
        "status_function": None,
        "box_attributes": ["BlockAckThreshold",
            "MinCw",
            "MaxCw",
            "Aifsn"],
        "factory_attributes": [],
        "traces": []
    )},
     "ns3::UanPhyPerGenDefault": dict{(
        "category": "",
        "create_function": create_element,
        "help": "",
        "connector_types": [],
        "allow_routes": False,
        "allow_addresses": False,
        "stop_function": None,
        "start_function": None,
        "status_function": None,
        "box_attributes": ["Threshold"],
        "factory_attributes": [],
        "traces": []
    )},
     "ns3::IdealWifiManager": dict{(
        "category": "Manager",
        "create_function": create_element,
        "help": "",
        "connector_types": ["dev"],
        "allow_routes": False,
        "allow_addresses": False,
        "stop_function": None,
        "start_function": None,
        "status_function": None,
        "box_attributes": ["BerThreshold",
            "IsLowLatency",
            "MaxSsrc",
            "MaxSlrc",
            "RtsCtsThreshold",
            "FragmentationThreshold",
            "NonUnicastMode"],
        "factory_attributes": [],
        "traces": []
    )},
     "ns3::MultiModelSpectrumChannel": dict{(
        "category": "Channel",
        "create_function": create_element,
        "help": "",
        "connector_types": [],
        "allow_routes": False,
        "allow_addresses": False,
        "stop_function": None,
        "start_function": None,
        "status_function": None,
        "box_attributes": [],
        "factory_attributes": [],
        "traces": []
    )},
     "ns3::HalfDuplexIdealPhy": dict{(
        "category": "Phy",
        "create_function": create_element,
        "help": "",
        "connector_types": [],
        "allow_routes": False,
        "allow_addresses": False,
        "stop_function": None,
        "start_function": None,
        "status_function": None,
        "box_attributes": ["Rate"],
        "factory_attributes": [],
        "traces": []
    )},
     "ns3::UanPhyCalcSinrDefault": dict{(
        "category": "Phy",
        "create_function": create_element,
        "help": "",
        "connector_types": [],
        "allow_routes": False,
        "allow_addresses": False,
        "stop_function": None,
        "start_function": None,
        "status_function": None,
        "box_attributes": [],
        "factory_attributes": [],
        "traces": []
    )},
     "ns3::ReceiveListErrorModel": dict{(
        "category": "Error",
        "create_function": create_element,
        "help": "",
        "connector_types": ["dev"],
        "allow_routes": False,
        "allow_addresses": False,
        "stop_function": None,
        "start_function": None,
        "status_function": None,
        "box_attributes": ["IsEnabled"],
        "factory_attributes": [],
        "traces": []
    )},
     "ns3::SpectrumAnalyzer": dict{(
        "category": "",
        "create_function": create_element,
        "help": "",
        "connector_types": [],
        "allow_routes": False,
        "allow_addresses": False,
        "stop_function": None,
        "start_function": None,
        "status_function": None,
        "box_attributes": ["Resolution",
        "NoisePowerSpectralDensity"],
        "factory_attributes": [],
        "traces": []
    )},
     "ns3::ConstantRateWifiManager": dict{(
        "category": "Manager",
        "create_function": create_element,
        "help": "",
        "connector_types": ["dev"],
        "allow_routes": False,
        "allow_addresses": False,
        "stop_function": None,
        "start_function": None,
        "status_function": None,
        "box_attributes": ["DataMode",
            "ControlMode",
            "IsLowLatency",
            "MaxSsrc",
            "MaxSlrc",
            "RtsCtsThreshold",
            "FragmentationThreshold",
            "NonUnicastMode"],
        "factory_attributes": [],
        "traces": []
    )},
     "ns3::Ipv6OptionPad1": dict{(
        "category": "",
        "create_function": create_element,
        "help": "",
        "connector_types": [],
        "allow_routes": False,
        "allow_addresses": False,
        "stop_function": None,
        "start_function": None,
        "status_function": None,
        "box_attributes": ["OptionNumber"],
        "factory_attributes": [],
        "traces": []
    )},
     "ns3::UdpTraceClient": dict{(
        "category": "",
        "create_function": create_element,
        "help": "",
        "connector_types": [],
        "allow_routes": False,
        "allow_addresses": False,
        "stop_function": None,
        "start_function": None,
        "status_function": None,
        "box_attributes": ["RemoteAddress",
            "RemotePort",
            "MaxPacketSize",
            "StartTime",
            "StopTime"],
        "factory_attributes": [],
        "traces": []
    )},
     "ns3::RraaWifiManager": dict{(
        "category": "Manager",
        "create_function": create_element,
        "help": "",
        "connector_types": ["dev"],
        "allow_routes": False,
        "allow_addresses": False,
        "stop_function": None,
        "start_function": None,
        "status_function": None,
        "box_attributes": ["Basic",
            "Timeout",
            "ewndFor54mbps",
            "ewndFor48mbps",
            "ewndFor36mbps",
            "ewndFor24mbps",
            "ewndFor18mbps",
            "ewndFor12mbps",
            "ewndFor9mbps",
            "ewndFor6mbps",
            "poriFor48mbps",
            "poriFor36mbps",
            "poriFor24mbps",
            "poriFor18mbps",
            "poriFor12mbps",
            "poriFor9mbps",
            "poriFor6mbps",
            "pmtlFor54mbps",
            "pmtlFor48mbps",
            "pmtlFor36mbps",
            "pmtlFor24mbps",
            "pmtlFor18mbps",
            "pmtlFor12mbps",
            "pmtlFor9mbps",
            "IsLowLatency",
            "MaxSsrc",
            "MaxSlrc",
            "RtsCtsThreshold",
            "FragmentationThreshold",
            "NonUnicastMode"],
        "factory_attributes": [],
        "traces": []
    )},
     "ns3::RandomPropagationLossModel": dict{(
        "category": "Loss",
        "create_function": create_element,
        "help": "",
        "connector_types": [],
        "allow_routes": False,
        "allow_addresses": False,
        "stop_function": None,
        "start_function": None,
        "status_function": None,
        "box_attributes": ["Variable"],
        "factory_attributes": [],
        "traces": []
    )},
     "ns3::UanChannel": dict{(
        "category": "Channel",
        "create_function": create_element,
        "help": "",
        "connector_types": [],
        "allow_routes": False,
        "allow_addresses": False,
        "stop_function": None,
        "start_function": None,
        "status_function": None,
        "box_attributes": [],
        "factory_attributes": [],
        "traces": []
    )},
     "ns3::MinstrelWifiManager": dict{(
        "category": "Manager",
        "create_function": create_element,
        "help": "",
        "connector_types": ["dev"],
        "allow_routes": False,
        "allow_addresses": False,
        "stop_function": None,
        "start_function": None,
        "status_function": None,
        "box_attributes": ["UpdateStatistics",
            "LookAroundRate",
            "EWMA",
            "SegmentSize",
            "SampleColumn",
            "PacketLength",
            "IsLowLatency",
            "MaxSsrc",
            "MaxSlrc",
            "RtsCtsThreshold",
            "FragmentationThreshold",
            "NonUnicastMode"],
        "factory_attributes": [],
        "traces": []
    )},
     "ns3::UanPhyDual": dict{(
        "category": "Phy",
        "create_function": create_element,
        "help": "",
        "connector_types": [],
        "allow_routes": False,
        "allow_addresses": False,
        "stop_function": None,
        "start_function": None,
        "status_function": None,
        "box_attributes": ["CcaThresholdPhy1",
            "CcaThresholdPhy2",
            "TxPowerPhy1",
            "TxPowerPhy2",
            "RxGainPhy1",
            "RxGainPhy2",
            "SupportedModesPhy1",
            "SupportedModesPhy2"],
        "factory_attributes": [],
        "traces": []
    )},
     "ns3::ListErrorModel": dict{(
        "category": "Error",
        "create_function": create_element,
        "help": "",
        "connector_types": ["dev"],
        "allow_routes": False,
        "allow_addresses": False,
        "stop_function": None,
        "start_function": None,
        "status_function": None,
        "box_attributes": ["IsEnabled"],
        "factory_attributes": [],
        "traces": []
    )},
     "ns3::VirtualNetDevice": dict{(
        "category": "Device",
        "create_function": create_device,
        "help": "",
        "connector_types": ["node"],
        "allow_routes": False,
        "allow_addresses": True,
        "stop_function": None,
        "start_function": None,
        "status_function": None,
        "box_attributes": ["Mtu"],
        "factory_attributes": [],
        "traces": []
    )},
     "ns3::UanPhyGen": dict{(
        "category": "Phy",
        "create_function": create_element,
        "help": "",
        "connector_types": [],
        "allow_routes": False,
        "allow_addresses": False,
        "stop_function": None,
        "start_function": None,
        "status_function": None,
        "box_attributes": ["CcaThreshold",
            "RxThreshold",
            "TxPower",
            "RxGain",
            "SupportedModes"],
        "factory_attributes": [],
        "traces": []
    )},
     "ns3::Ipv6L3Protocol": dict{(
        "category": "Protocol",
        "create_function": create_element,
        "help": "",
        "connector_types": ["node"],
        "allow_routes": False,
        "allow_addresses": False,
        "stop_function": None,
        "start_function": None,
        "status_function": None,
        "box_attributes": ["DefaultTtl",
            "IpForward"],
        "factory_attributes": [],
        "traces": []
    )},
     "ns3::PointToPointRemoteChannel": dict{(
        "category": "Channel",
        "create_function": create_element,
        "help": "",
        "connector_types": [],
        "allow_routes": False,
        "allow_addresses": False,
        "stop_function": None,
        "start_function": None,
        "status_function": None,
        "box_attributes": ["Delay"],
        "factory_attributes": [],
        "traces": []
    )},
     "ns3::UanPhyPerUmodem": dict{(
        "category": "Phy",
        "create_function": create_element,
        "help": "",
        "connector_types": [],
        "allow_routes": False,
        "allow_addresses": False,
        "stop_function": None,
        "start_function": None,
        "status_function": None,
        "box_attributes": [],
        "factory_attributes": [],
        "traces": []
    )},
     "ns3::OnoeWifiManager": dict{(
        "category": "Manager",
        "create_function": create_element,
        "help": "",
        "connector_types": ["dev"],
        "allow_routes": False,
        "allow_addresses": False,
        "stop_function": None,
        "start_function": None,
        "status_function": None,
        "box_attributes": ["UpdatePeriod",
            "RaiseThreshold",
            "AddCreditThreshold",
            "IsLowLatency",
            "MaxSsrc",
            "MaxSlrc",
            "RtsCtsThreshold",
            "FragmentationThreshold",
            "NonUnicastMode"],
        "factory_attributes": [],
        "traces": []
    )},
     "ns3::QadhocWifiMac": dict{(
        "category": "Mac",
        "create_function": create_element,
        "help": "",
        "connector_types": [],
        "allow_routes": False,
        "allow_addresses": False,
        "stop_function": None,
        "start_function": None,
        "status_function": None,
        "box_attributes": ["CtsTimeout",
            "AckTimeout",
            "BasicBlockAckTimeout",
            "CompressedBlockAckTimeout",
            "Sifs",
            "EifsNoDifs",
            "Slot",
            "Pifs",
            "MaxPropagationDelay",
            "Ssid"],
        "factory_attributes": [],
        "traces": []
    )},
     "ns3::JakesPropagationLossModel": dict{(
        "category": "Loss",
        "create_function": create_element,
        "help": "",
        "connector_types": [],
        "allow_routes": False,
        "allow_addresses": False,
        "stop_function": None,
        "start_function": None,
        "status_function": None,
        "box_attributes": ["NumberOfRaysPerPath",
            "NumberOfOscillatorsPerRay",
            "DopplerFreq",
            "Distribution"],
        "factory_attributes": [],
        "traces": []
    )},
     "ns3::PacketSink": dict{(
        "category": "Application",
        "create_function": create_element,
        "help": "",
        "connector_types": ["node"],
        "allow_routes": False,
        "allow_addresses": False,
        "stop_function": stop_application,
        "start_function": start_application,
        "status_function": status_application,
        "box_attributes": ["Local",
            "Protocol",
            "StartTime",
            "StopTime"],
        "factory_attributes": [],
        "traces": []
    )},
     "ns3::RandomDirection2dMobilityModel": dict{(
        "category": "Mobility",
        "create_function": create_element,
        "help": "",
        "connector_types": ["node"],
        "allow_routes": False,
        "allow_addresses": False,
        "stop_function": None,
        "start_function": None,
        "status_function": None,
        "box_attributes": ["Bounds",
            "Speed",
            "Pause",
            "Position",
            "Velocity"],
        "factory_attributes": [],
        "traces": []
    )},
     "ns3::UanMacAloha": dict{(
        "category": "",
        "create_function": create_element,
        "help": "",
        "connector_types": [],
        "allow_routes": False,
        "allow_addresses": False,
        "stop_function": None,
        "start_function": None,
        "status_function": None,
        "box_attributes": [],
        "factory_attributes": [],
        "traces": []
    )},
     "ns3::MsduStandardAggregator": dict{(
        "category": "",
        "create_function": create_element,
        "help": "",
        "connector_types": [],
        "allow_routes": False,
        "allow_addresses": False,
        "stop_function": None,
        "start_function": None,
        "status_function": None,
        "box_attributes": ["MaxAmsduSize"],
        "factory_attributes": [],
        "traces": []
    )},
     "ns3::DcaTxop": dict{(
        "category": "",
        "create_function": create_element,
        "help": "",
        "connector_types": [],
        "allow_routes": False,
        "allow_addresses": False,
        "stop_function": None,
        "start_function": None,
        "status_function": None,
        "box_attributes": ["MinCw",
            "MaxCw",
            "Aifsn"],
        "factory_attributes": [],
        "traces": []
    )},
     "ns3::UanPhyCalcSinrFhFsk": dict{(
        "category": "Phy",
        "create_function": create_element,
        "help": "",
        "connector_types": [],
        "allow_routes": False,
        "allow_addresses": False,
        "stop_function": None,
        "start_function": None,
        "status_function": None,
        "box_attributes": ["NumberOfHops"],
        "factory_attributes": [],
        "traces": []
    )},
     "ns3::UanPropModelIdeal": dict{(
        "category": "",
        "create_function": create_element,
        "help": "",
        "connector_types": [],
        "allow_routes": False,
        "allow_addresses": False,
        "stop_function": None,
        "start_function": None,
        "status_function": None,
        "box_attributes": [],
        "factory_attributes": [],
        "traces": []
    )},
     "ns3::UanMacRcGw": dict{(
        "category": "",
        "create_function": create_element,
        "help": "",
        "connector_types": [],
        "allow_routes": False,
        "allow_addresses": False,
        "stop_function": None,
        "start_function": None,
        "status_function": None,
        "box_attributes": ["MaxReservations",
            "NumberOfRates",
            "RetryRate",
            "MaxPropDelay",
            "SIFS",
            "NumberOfNodes",
            "MinRetryRate",
            "RetryStep",
            "NumberOfRetryRates",
            "TotalRate",
            "RateStep",
            "FrameSize"],
        "factory_attributes": [],
        "traces": []
    )},
     "ns3::NistErrorRateModel": dict{(
        "category": "Error",
        "create_function": create_element,
        "help": "",
        "connector_types": ["phy"],
        "allow_routes": False,
        "allow_addresses": False,
        "stop_function": None,
        "start_function": None,
        "status_function": None,
        "box_attributes": [],
        "factory_attributes": [],
        "traces": []
    )},
     "ns3::Ipv4L3Protocol": dict{(
        "category": "Protocol",
        "create_function": create_ipv4stack,
        "help": "",
        "connector_types": ["node"],
        "allow_routes": False,
        "allow_addresses": False,
        "stop_function": None,
        "start_function": None,
        "status_function": None,
        "box_attributes": ["DefaultTtl",
            "IpForward",
            "WeakEsModel"],
        "factory_attributes": [],
        "traces": []
    )},
     "ns3::aodv::RoutingProtocol": dict{(
        "category": "Protocol",
        "create_function": create_element,
        "help": "",
        "connector_types": ["node"],
        "allow_routes": False,
        "allow_addresses": False,
        "stop_function": None,
        "start_function": None,
        "status_function": None,
        "box_attributes": ["HelloInterval",
            "RreqRetries",
            "RreqRateLimit",
            "NodeTraversalTime",
            "NextHopWait",
            "ActiveRouteTimeout",
            "MyRouteTimeout",
            "BlackListTimeout",
            "DeletePeriod",
            "TimeoutBuffer",
            "NetDiameter",
            "NetTraversalTime",
            "PathDiscoveryTime",
            "MaxQueueLen",
            "MaxQueueTime",
            "AllowedHelloLoss",
            "GratuitousReply",
            "DestinationOnly",
            "EnableHello",
            "EnableBroadcast"],
        "factory_attributes": [],
        "traces": []
    )},
     "ns3::TcpL4Protocol": dict{(
        "category": "Protocol",
        "create_function": create_element,
        "help": "",
        "connector_types": ["node"],
        "allow_routes": False,
        "allow_addresses": False,
        "stop_function": None,
        "start_function": None,
        "status_function": None,
        "box_attributes": ["RttEstimatorFactory",
            "ProtocolNumber"],
        "factory_attributes": [],
        "traces": []
    )},
     "ns3::olsr::RoutingProtocol": dict{(
        "category": "Protocol",
        "create_function": create_element,
        "help": "",
        "connector_types": ["node"],
        "allow_routes": False,
        "allow_addresses": False,
        "stop_function": None,
        "start_function": None,
        "status_function": None,
        "box_attributes": ["HelloInterval",
            "TcInterval",
            "MidInterval",
            "HnaInterval",
            "Willingness"],
        "factory_attributes": [],
        "traces": []
    )},
     "ns3::UdpEchoServer": dict{(
        "category": "Application",
        "create_function": create_element,
        "help": "",
        "connector_types": ["node"],
        "allow_routes": False,
        "allow_addresses": False,
        "stop_function": stop_application,
        "start_function": start_application,
        "status_function": status_application,
        "box_attributes": ["Port",
           "StartTime",
           "StopTime"],
        "factory_attributes": [],
        "traces": []
    )},
     "ns3::AmrrWifiManager": dict{(
        "category": "Manager",
        "create_function": create_element,
        "help": "",
        "connector_types": ["dev"],
        "allow_routes": False,
        "allow_addresses": False,
        "stop_function": None,
        "start_function": None,
        "status_function": None,
        "box_attributes": ["UpdatePeriod",
            "FailureRatio",
            "SuccessRatio",
            "MaxSuccessThreshold",
            "MinSuccessThreshold",
            "IsLowLatency",
            "MaxSsrc",
            "MaxSlrc",
            "RtsCtsThreshold",
            "FragmentationThreshold",
            "NonUnicastMode"],
        "factory_attributes": [],
        "traces": []
    )},
     "ns3::ArfWifiManager": dict{(
        "category": "Manager",
        "create_function": create_element,
        "help": "",
        "connector_types": ["dev"],
        "allow_routes": False,
        "allow_addresses": False,
        "stop_function": None,
        "start_function": None,
        "status_function": None,
        "box_attributes": ["TimerThreshold",
            "SuccessThreshold",
            "IsLowLatency",
            "MaxSsrc",
            "MaxSlrc",
            "RtsCtsThreshold",
            "FragmentationThreshold",
            "NonUnicastMode"],
        "factory_attributes": [],
        "traces": []
    )},
     "ns3::SubscriberStationNetDevice": dict{(
        "category": "Device",
        "create_function": create_device,
        "help": "",
        "connector_types": ["node"],
        "allow_routes": False,
        "allow_addresses": True,
        "stop_function": None,
        "start_function": None,
        "status_function": None,
        "box_attributes": ["LostDlMapInterval",
            "LostUlMapInterval",
            "MaxDcdInterval",
            "MaxUcdInterval",
            "IntervalT1",
            "IntervalT2",
            "IntervalT3",
            "IntervalT7",
            "IntervalT12",
            "IntervalT20",
            "IntervalT21",
            "MaxContentionRangingRetries",
            "Mtu",
            "RTG",
            "TTG"],
        "factory_attributes": [],
        "traces": []
    )},
     "ns3::flame::FlameRtable": dict{(
        "category": "",
        "create_function": create_element,
        "help": "",
        "connector_types": [],
        "allow_routes": False,
        "allow_addresses": False,
        "stop_function": None,
        "start_function": None,
        "status_function": None,
        "box_attributes": ["Lifetime"],
        "factory_attributes": [],
        "traces": []
    )},
)}
